---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: python-checks
  pull: always
  image: python
  commands:
    - pip install black prospector[with_bandit,with_vulture]
    - pip install -r requirements.txt
    - prospector --with-tool vulture --with-tool bandit --without-tool mccabe main.py
    - black --check main.py


- name: build
  pull: always
  image: spritsail/docker-build
  settings:
    repo: whostole-dev

- name: publish
  pull: always
  image: spritsail/docker-publish
  settings:
    from: whostole-dev
    repo: adamant/minecraft-whostole
    tags:
    - latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch:
    - master
    event:
    - tag
    - push
---
kind: signature
hmac: c017e0a3e4f5597843aadec031db92aa6974466a70464365e3468cc2cbea096b

...
